version: '3.4'

services:
  server:
    image: nginx
    volumes:
      - ./:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${APP_PORT}:80
    networks:
      - backend

  app:
    build: .docker/php/production.Dockerfile
    image: php:7.4
    volumes:
      - ./:/var/www/html:rw
      - .docker/php/policy.xml:/etc/ImageMagick-6/policy.xml:ro
    networks:
      - backend

networks:
  backend:
